# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Publish Maven Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set package version
      run: echo "::set-env name=PACKAGE_VERSION::${{ env.MAIN_VER }}.${{ github.run_number }}.$(date +"%y%m%d")"
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Publish to GitHub Packages Apache Maven
      run: |
        sed -i 's/${PACKAGE_VERSION}/${{ env.PACKAGE_VERSION }}/g' pom.xml
        mvn deploy -s settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SAS_REPO_TOKEN: ${{ secrets.SAS_REPO_TOKEN }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ env.PACKAGE_VERSION }}
        release_name: Release-${{ env.PACKAGE_VERSION }}
        body: |
          Changes in this Release
          - Update Copy Script
          - Update Maven Job
        draft: false
        prerelease: false
